type MCQSeed = {
  questionText: string;
  options: [string, string, string, string];
  correctAnswer: number;
  category: 'cyber' | 'logic' | 'coding';
  difficulty: 'easy' | 'medium' | 'hard';
  points: number;
  order: number;
};

type TestCase = { input: string; expectedOutput: string };

type CodingSeed = {
  title: string;
  description: string;
  inputFormat: string;
  outputFormat: string;
  constraints: string;
  sampleInput: string;
  sampleOutput: string;
  hiddenTestCases: TestCase[];
  difficulty: 'easy' | 'medium' | 'hard';
  points: number;
  timeLimit: number;
  memoryLimit: number;
  order: number;
  starterCode: Record<'c' | 'cpp' | 'java' | 'python', string>;
  wrappers?: Partial<Record<'c' | 'cpp' | 'java' | 'python', string>>;
};

export const ROUND1_MCQ_BANK: MCQSeed[] = [
  // ── MEDIUM (10 questions, 1 point each) ──
  {
    questionText: 'A virus is spreading through a network represented as a tree. Which traversal identifies the depth of the infection first?',
    options: ['Pre-order', 'In-order', 'Post-order', 'Level-order (BFS)'],
    correctAnswer: 3,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 1,
  },
  {
    questionText: 'In C++, if an agent class inherits from "Person" and has a private "identity", can a "FieldAgent" subclass access "identity" if it is protected in "Person"?',
    options: ['Yes', 'No', 'Only if static', 'Only with a friend function'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 2,
  },
  {
    questionText: 'An agent\'s code has an O(n^2) loop. If n=10 takes 1 second, how long (roughly) will n=100 take?',
    options: ['10s', '100s', '1000s', '20s'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 3,
  },
  {
    questionText: 'A man-in-the-middle attack targets which security property primarily?',
    options: ['Confidentiality', 'Availability', 'Integrity', 'Accountability'],
    correctAnswer: 2,
    category: 'cyber',
    difficulty: 'medium',
    points: 1,
    order: 4,
  },
  {
    questionText: 'If a recursive function for "SpyCount" does not have a base case, what happens?',
    options: ['Returns 0', 'Returns null', 'Stack Overflow', 'Infinite loop (no memory issue)'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 5,
  },
  {
    questionText: 'Which sorting algorithm has the best worst-case time complexity?',
    options: ['Bubble Sort', 'Quick Sort', 'Merge Sort', 'Insertion Sort'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 6,
  },
  {
    questionText: 'In JavaScript, what is "typeof NaN"?',
    options: ['number', 'string', 'undefined', 'object'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 7,
  },
  {
    questionText: 'Which data structure is suitable for a Breadth-First Search on a network graph?',
    options: ['Stack', 'Queue', 'Priority Queue', 'Tree'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 8,
  },
  {
    questionText: 'In Python, what is the output of [1,2,3][::-1]?',
    options: ['[1,2,3]', '[3,2,1]', '[1,3]', 'Error'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'medium',
    points: 1,
    order: 9,
  },
  {
    questionText: 'A hash table resolves collisions using chaining. What is the worst-case lookup time if all keys hash to the same bucket?',
    options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'medium',
    points: 1,
    order: 10,
  },
  // ── HARD (20 questions, 2 points each) ──
  {
    questionText: 'A directed reconnaissance graph needs all strongly connected components in linear time. Which algorithm is designed for that task?',
    options: ['Dijkstra with a min-heap', 'Tarjan or Kosaraju SCC decomposition', 'Prim with path compression', 'Floyd-Warshall with pruning'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 11,
  },
  {
    questionText: 'An infiltration map has negative edge weights but no negative cycles. Which shortest-path algorithm remains correct from a single source?',
    options: ['Breadth-first search', 'Dijkstra with a heap', 'Bellman-Ford', 'Prim'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 12,
  },
  {
    questionText: 'You must process millions of UNION and FIND operations on agent clusters. Which structure gives near-constant amortized performance?',
    options: ['Binary indexed tree', 'Disjoint-set union with path compression and union by rank', 'Sorted vector with binary search', 'Adjacency matrix'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 13,
  },
  {
    questionText: 'Which data structure gives an O(n) solution for maximum values over every sliding window of size k?',
    options: ['Balanced BST only', 'Priority queue with lazy deletion only', 'Monotonic deque', 'Union-find'],
    correctAnswer: 2,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 14,
  },
  {
    questionText: 'The graph of safehouses is a DAG, and you need the longest achievable route. Which approach is correct?',
    options: ['Run Dijkstra from every node', 'Use topological ordering followed by dynamic programming', 'Use union-find on all edges', 'Binary search over path lengths only'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'hard',
    points: 2,
    order: 15,
  },
  {
    questionText: 'A rooted tree receives up to 10^5 lowest-common-ancestor queries with no structural updates. Which preprocessing strategy is standard?',
    options: ['Bellman-Ford on the tree', 'Binary lifting over parent powers', 'Kruskal on all edges', 'Mo\'s algorithm on arrays'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 16,
  },
  {
    questionText: 'You need point updates and range minimum queries on an array of risk scores. Which structure is the most direct fit?',
    options: ['Prefix sums', 'Segment tree', 'Queue', 'Hash set'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 17,
  },
  {
    questionText: 'By Master Theorem, what is the asymptotic complexity of T(n) = 2T(n/2) + n log n?',
    options: ['O(n log n)', 'O(n log^2 n)', 'O(n^2)', 'O(log^2 n)'],
    correctAnswer: 1,
    category: 'logic',
    difficulty: 'hard',
    points: 2,
    order: 18,
  },
  {
    questionText: 'Which technique counts subarrays with sum exactly k in O(n) time over arbitrary integers?',
    options: ['Two pointers only', 'Prefix sums with a frequency hash map', 'Sorting the array first', 'Union-find over indices'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 19,
  },
  {
    questionText: 'To implement an O(1) LRU cache, which paired structures are normally required?',
    options: ['Binary heap and hash set', 'Hash map and doubly linked list', 'Trie and segment tree', 'Queue and prefix sums'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 20,
  },
  {
    questionText: 'For a session that authenticates users via cookies, which defense is the most robust against CSRF?',
    options: ['Base64-encoding the cookie', 'Synchronizer CSRF token plus SameSite cookie policy', 'Rotating CSS class names', 'Client-side password hashing only'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 21,
  },
  {
    questionText: 'Which password-storage strategy is appropriate for resisting offline GPU cracking after a database leak?',
    options: ['Plain SHA-256 without salt', 'AES encrypt every password with the same key', 'Argon2id or bcrypt with a unique per-user salt', 'Base64-encode and store'],
    correctAnswer: 2,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 22,
  },
  {
    questionText: 'An access token must be compared without leaking prefix matches via timing. What should the server use?',
    options: ['A lexicographic comparison', 'A constant-time equality check', 'A regex with backtracking', 'String hashing with no verification'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 23,
  },
  {
    questionText: 'Which outbound request policy is the right baseline mitigation for server-side request forgery (SSRF)?',
    options: ['Allow any URL but log it', 'Resolve hostnames client-side only', 'Enforce a strict allowlist and block private/internal address ranges', 'Disable TLS verification'],
    correctAnswer: 2,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 24,
  },
  {
    questionText: 'A backend builds SQL by concatenating user input into WHERE clauses. Which fix is correct?',
    options: ['Escape only single quotes on the frontend', 'Use parameterized queries/prepared statements', 'URL-encode the full query string', 'Hash the SQL before executing it'],
    correctAnswer: 1,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 25,
  },
  {
    questionText: 'A file authorization check passes, but the file path can change before use. Which class of bug is this?',
    options: ['TOCTOU race condition', 'Deadlock', 'Heap fragmentation', 'Tail-call elimination'],
    correctAnswer: 0,
    category: 'cyber',
    difficulty: 'hard',
    points: 2,
    order: 26,
  },
  {
    questionText: 'For a positive integer x, what does the expression x & (x - 1) equal when x is a power of two?',
    options: ['1', 'x', '0', '-1'],
    correctAnswer: 2,
    category: 'logic',
    difficulty: 'hard',
    points: 2,
    order: 27,
  },
  {
    questionText: 'Which structure supports online median queries over a stream in O(log n) update time?',
    options: ['Two heaps maintaining lower and upper halves', 'One stack and one queue', 'Prefix XOR table', 'Union-find over values'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 28,
  },
  {
    questionText: 'The classic Word Break problem asks whether a string can be segmented using a dictionary. Which core approach is standard?',
    options: ['Dynamic programming on prefix reachability', 'Quickselect on substrings', 'Tarjan SCC on characters', 'Heap sort over token lengths'],
    correctAnswer: 0,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 29,
  },
  {
    questionText: 'To find the minimum window of s containing every character of pattern t, which strategy is expected from an optimal solution?',
    options: ['Suffix array construction', 'Sliding window with frequency deficits', 'Union-find on character indices', 'Depth-first search over all substrings'],
    correctAnswer: 1,
    category: 'coding',
    difficulty: 'hard',
    points: 2,
    order: 30,
  },
];

const ID_INPUT = 'The first line contains an integer n. The second line contains n integers representing dossier values.';
const DEFAULT_CONSTRAINTS = '1 <= n <= 2 * 10^5\nValues fit in 32-bit signed integers.';

const STANDARD_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n\nint main(void) {\n    // Write your solution here.\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n    // Write your solution here.\n    return 0;\n}\n',
  java: 'import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        // Write your solution here.\n    }\n}\n',
  python: '# Write your solution here.\n',
};

const REGISTRY_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct Registry Registry;\n\nRegistry* create_registry(void) {\n    return NULL;\n}\n\nvoid add_agent(Registry* registry, const char* code, int score) {\n}\n\nvoid update_agent(Registry* registry, const char* code, int delta) {\n}\n\nint get_score(Registry* registry, const char* code) {\n    return -1;\n}\n\nint top_score(Registry* registry) {\n    return -1;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass Registry {\npublic:\n    void addAgent(const string& code, int score) {\n    }\n\n    void updateAgent(const string& code, int delta) {\n    }\n\n    int getScore(const string& code) {\n        return -1;\n    }\n\n    int topScore() {\n        return -1;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass Registry {\n    public void addAgent(String code, int score) {\n    }\n\n    public void updateAgent(String code, int delta) {\n    }\n\n    public int getScore(String code) {\n        return -1;\n    }\n\n    public int topScore() {\n        return -1;\n    }\n}\n',
  python: 'class Registry:\n    def __init__(self):\n        pass\n\n    def add_agent(self, code: str, score: int) -> None:\n        pass\n\n    def update_agent(self, code: str, delta: int) -> None:\n        pass\n\n    def get_score(self, code: str) -> int:\n        return -1\n\n    def top_score(self) -> int:\n        return -1\n',
};

const INVENTORY_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct Inventory Inventory;\n\nInventory* create_inventory(void) {\n    return NULL;\n}\n\nvoid stock_item(Inventory* inventory, const char* itemType, int count) {\n}\n\nvoid use_item(Inventory* inventory, const char* itemType, int count) {\n}\n\nint count_item(Inventory* inventory, const char* itemType) {\n    return 0;\n}\n\nint total_items(Inventory* inventory) {\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass Inventory {\npublic:\n    void stockItem(const string& itemType, int count) {\n    }\n\n    void useItem(const string& itemType, int count) {\n    }\n\n    int countItem(const string& itemType) {\n        return 0;\n    }\n\n    int totalItems() {\n        return 0;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass Inventory {\n    public void stockItem(String itemType, int count) {\n    }\n\n    public void useItem(String itemType, int count) {\n    }\n\n    public int countItem(String itemType) {\n        return 0;\n    }\n\n    public int totalItems() {\n        return 0;\n    }\n}\n',
  python: 'class Inventory:\n    def __init__(self):\n        pass\n\n    def stock_item(self, item_type: str, count: int) -> None:\n        pass\n\n    def use_item(self, item_type: str, count: int) -> None:\n        pass\n\n    def count_item(self, item_type: str) -> int:\n        return 0\n\n    def total_items(self) -> int:\n        return 0\n',
};

const ANALYZER_STARTER: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdlib.h>\n#include <string.h>\n\ntypedef struct ReportAnalyzer ReportAnalyzer;\n\nReportAnalyzer* create_analyzer(void) {\n    return NULL;\n}\n\nvoid add_report(ReportAnalyzer* analyzer, const char* word) {\n}\n\nint has_report(ReportAnalyzer* analyzer, const char* word) {\n    return 0;\n}\n\nint longest_report(ReportAnalyzer* analyzer) {\n    return 0;\n}\n\nint report_count(ReportAnalyzer* analyzer) {\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\nclass ReportAnalyzer {\npublic:\n    void addReport(const string& word) {\n    }\n\n    bool hasReport(const string& word) {\n        return false;\n    }\n\n    int longestReport() {\n        return 0;\n    }\n\n    int reportCount() {\n        return 0;\n    }\n};\n',
  java: 'import java.util.*;\n\nclass ReportAnalyzer {\n    public void addReport(String word) {\n    }\n\n    public boolean hasReport(String word) {\n        return false;\n    }\n\n    public int longestReport() {\n        return 0;\n    }\n\n    public int reportCount() {\n        return 0;\n    }\n}\n',
  python: 'class ReportAnalyzer:\n    def __init__(self):\n        pass\n\n    def add_report(self, word: str) -> None:\n        pass\n\n    def has_report(self, word: str) -> bool:\n        return False\n\n    def longest_report(self) -> int:\n        return 0\n\n    def report_count(self) -> int:\n        return 0\n',
};

const REGISTRY_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct Entry {\n    char code[64];\n    int score;\n} Entry;\n\nstruct Registry {\n    Entry items[200005];\n    int size;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    Registry* registry = create_registry();\n    char cmd[16], code[64];\n    int value;\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"ADD\") == 0) {\n            scanf(\"%63s %d\", code, &value);\n            add_agent(registry, code, value);\n        } else if (strcmp(cmd, \"UPDATE\") == 0) {\n            scanf(\"%63s %d\", code, &value);\n            update_agent(registry, code, value);\n        } else if (strcmp(cmd, \"GET\") == 0) {\n            scanf(\"%63s\", code);\n            printf(\"%d\\n\", get_score(registry, code));\n        } else {\n            int best = top_score(registry);\n            if (best == -1) printf(\"EMPTY\\n\");\n            else printf(\"%d\\n\", best);\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    Registry registry;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"ADD\") {\n            string code;\n            int score;\n            cin >> code >> score;\n            registry.addAgent(code, score);\n        } else if (cmd == \"UPDATE\") {\n            string code;\n            int delta;\n            cin >> code >> delta;\n            registry.updateAgent(code, delta);\n        } else if (cmd == \"GET\") {\n            string code;\n            cin >> code;\n            cout << registry.getScore(code) << \"\\n\";\n        } else {\n            int best = registry.topScore();\n            if (best == -1) cout << \"EMPTY\\n\";\n            else cout << best << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        Registry registry = new Registry();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"ADD\".equals(cmd)) {\n                registry.addAgent(sc.next(), sc.nextInt());\n            } else if (\"UPDATE\".equals(cmd)) {\n                registry.updateAgent(sc.next(), sc.nextInt());\n            } else if (\"GET\".equals(cmd)) {\n                out.append(registry.getScore(sc.next())).append(\'\\n\');\n            } else {\n                int best = registry.topScore();\n                out.append(best == -1 ? \"EMPTY\" : Integer.toString(best)).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    registry = Registry()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"ADD\":\n            registry.add_agent(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"UPDATE\":\n            registry.update_agent(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"GET\":\n            out.append(str(registry.get_score(data[idx])))\n            idx += 1\n        else:\n            best = registry.top_score()\n            out.append(\"EMPTY\" if best == -1 else str(best))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

const INVENTORY_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct ItemEntry {\n    char name[64];\n    int count;\n} ItemEntry;\n\nstruct Inventory {\n    ItemEntry items[200005];\n    int size;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    Inventory* inventory = create_inventory();\n    char cmd[16], item[64];\n    int count;\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"STOCK\") == 0) {\n            scanf(\"%63s %d\", item, &count);\n            stock_item(inventory, item, count);\n        } else if (strcmp(cmd, \"USE\") == 0) {\n            scanf(\"%63s %d\", item, &count);\n            use_item(inventory, item, count);\n        } else if (strcmp(cmd, \"COUNT\") == 0) {\n            scanf(\"%63s\", item);\n            printf(\"%d\\n\", count_item(inventory, item));\n        } else {\n            printf(\"%d\\n\", total_items(inventory));\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    Inventory inventory;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"STOCK\") {\n            string item;\n            int count;\n            cin >> item >> count;\n            inventory.stockItem(item, count);\n        } else if (cmd == \"USE\") {\n            string item;\n            int count;\n            cin >> item >> count;\n            inventory.useItem(item, count);\n        } else if (cmd == \"COUNT\") {\n            string item;\n            cin >> item;\n            cout << inventory.countItem(item) << \"\\n\";\n        } else {\n            cout << inventory.totalItems() << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        Inventory inventory = new Inventory();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"STOCK\".equals(cmd)) {\n                inventory.stockItem(sc.next(), sc.nextInt());\n            } else if (\"USE\".equals(cmd)) {\n                inventory.useItem(sc.next(), sc.nextInt());\n            } else if (\"COUNT\".equals(cmd)) {\n                out.append(inventory.countItem(sc.next())).append(\'\\n\');\n            } else {\n                out.append(inventory.totalItems()).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    inventory = Inventory()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"STOCK\":\n            inventory.stock_item(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"USE\":\n            inventory.use_item(data[idx], int(data[idx + 1]))\n            idx += 2\n        elif cmd == \"COUNT\":\n            out.append(str(inventory.count_item(data[idx])))\n            idx += 1\n        else:\n            out.append(str(inventory.total_items()))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

const ANALYZER_WRAPPERS: Record<'c' | 'cpp' | 'java' | 'python', string> = {
  c: '#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n__USER_CODE__\n\ntypedef struct ReportEntry {\n    char word[128];\n} ReportEntry;\n\nstruct ReportAnalyzer {\n    ReportEntry items[200005];\n    int size;\n    int longest;\n};\n\nint main(void) {\n    int q;\n    if (scanf(\"%d\", &q) != 1) return 0;\n    ReportAnalyzer* analyzer = create_analyzer();\n    char cmd[16], word[128];\n    while (q--) {\n        scanf(\"%15s\", cmd);\n        if (strcmp(cmd, \"ADD\") == 0) {\n            scanf(\"%127s\", word);\n            add_report(analyzer, word);\n        } else if (strcmp(cmd, \"HAS\") == 0) {\n            scanf(\"%127s\", word);\n            printf(has_report(analyzer, word) ? \"YES\\n\" : \"NO\\n\");\n        } else if (strcmp(cmd, \"LONGEST\") == 0) {\n            printf(\"%d\\n\", longest_report(analyzer));\n        } else {\n            printf(\"%d\\n\", report_count(analyzer));\n        }\n    }\n    return 0;\n}\n',
  cpp: '#include <bits/stdc++.h>\nusing namespace std;\n\n__USER_CODE__\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int q;\n    if (!(cin >> q)) return 0;\n    ReportAnalyzer analyzer;\n    while (q--) {\n        string cmd;\n        cin >> cmd;\n        if (cmd == \"ADD\") {\n            string word;\n            cin >> word;\n            analyzer.addReport(word);\n        } else if (cmd == \"HAS\") {\n            string word;\n            cin >> word;\n            cout << (analyzer.hasReport(word) ? \"YES\" : \"NO\") << \"\\n\";\n        } else if (cmd == \"LONGEST\") {\n            cout << analyzer.longestReport() << \"\\n\";\n        } else {\n            cout << analyzer.reportCount() << \"\\n\";\n        }\n    }\n    return 0;\n}\n',
  java: 'import java.util.*;\n\n__USER_CODE__\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int q = sc.nextInt();\n        ReportAnalyzer analyzer = new ReportAnalyzer();\n        StringBuilder out = new StringBuilder();\n        while (q-- > 0) {\n            String cmd = sc.next();\n            if (\"ADD\".equals(cmd)) {\n                analyzer.addReport(sc.next());\n            } else if (\"HAS\".equals(cmd)) {\n                out.append(analyzer.hasReport(sc.next()) ? \"YES\" : \"NO\").append(\'\\n\');\n            } else if (\"LONGEST\".equals(cmd)) {\n                out.append(analyzer.longestReport()).append(\'\\n\');\n            } else {\n                out.append(analyzer.reportCount()).append(\'\\n\');\n            }\n        }\n        System.out.print(out);\n    }\n}\n',
  python: '__USER_CODE__\n\nimport sys\n\n\ndef main() -> None:\n    data = sys.stdin.read().strip().split()\n    if not data:\n        return\n    q = int(data[0])\n    idx = 1\n    analyzer = ReportAnalyzer()\n    out = []\n    for _ in range(q):\n        cmd = data[idx]\n        idx += 1\n        if cmd == \"ADD\":\n            analyzer.add_report(data[idx])\n            idx += 1\n        elif cmd == \"HAS\":\n            out.append(\"YES\" if analyzer.has_report(data[idx]) else \"NO\")\n            idx += 1\n        elif cmd == \"LONGEST\":\n            out.append(str(analyzer.longest_report()))\n        else:\n            out.append(str(analyzer.report_count()))\n    sys.stdout.write(\"\\n\".join(out))\n    if out:\n        sys.stdout.write(\"\\n\")\n\n\nif __name__ == \"__main__\":\n    main()\n',
};

export const ROUND2_CODING_BANK: CodingSeed[] = [
  {
    title: 'Mission Ledger Sweep',
    description: 'Return the maximum sum of any contiguous segment in the dossier values.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the maximum contiguous subarray sum.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '8\n-2 1 -3 4 -1 2 1 -5\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: '5\n1 2 3 4 5\n', expectedOutput: '15\n' },
      { input: '4\n-8 -3 -6 -2\n', expectedOutput: '-2\n' },
      { input: '6\n5 -2 7 -3 4 -1\n', expectedOutput: '11\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 1,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Cipher Window',
    description: 'Find the length of the longest substring without repeating characters in the incoming message.',
    inputFormat: 'A single lowercase string s.',
    outputFormat: 'Print the maximum length.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'abcaefbg\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: 'bbbb\n', expectedOutput: '1\n' },
      { input: 'pwwkew\n', expectedOutput: '3\n' },
      { input: 'mission\n', expectedOutput: '4\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 2,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Rooftop Extraction Route',
    description: 'Compute the water trapped between rooftop heights after a storm.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the total trapped water.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '12\n0 1 0 2 1 0 1 3 2 1 2 1\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: '6\n4 2 0 3 2 5\n', expectedOutput: '9\n' },
      { input: '5\n5 4 3 2 1\n', expectedOutput: '0\n' },
      { input: '5\n1 0 1 0 1\n', expectedOutput: '2\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 3,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Silent Stack Decoder',
    description: 'Verify whether the bracket sequence is balanced.',
    inputFormat: 'A single string containing only (), [] and {}.',
    outputFormat: 'Print VALID or INVALID.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: '{[()()]}\n',
    sampleOutput: 'VALID\n',
    hiddenTestCases: [
      { input: '([)]\n', expectedOutput: 'INVALID\n' },
      { input: '(((())))\n', expectedOutput: 'VALID\n' },
      { input: ']{\n', expectedOutput: 'INVALID\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 4,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Asset BST Confirmation',
    description: 'Given a binary tree in level order with -1 for null, determine whether it is a valid BST.',
    inputFormat: 'The first line contains n. The second line contains n integers in level order where -1 means null.',
    outputFormat: 'Print YES if valid, otherwise NO.',
    constraints: '1 <= n <= 2 * 10^5',
    sampleInput: '7\n8 4 10 2 6 9 12\n',
    sampleOutput: 'YES\n',
    hiddenTestCases: [
      { input: '7\n5 1 4 -1 -1 3 6\n', expectedOutput: 'NO\n' },
      { input: '3\n2 1 3\n', expectedOutput: 'YES\n' },
      { input: '5\n10 5 15 -1 -1 6 20\n', expectedOutput: 'NO\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 5,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Intercept Merge',
    description: 'Merge two sorted intercepted streams into one sorted output.',
    inputFormat: 'The first line contains n and m. The second line has n sorted integers. The third line has m sorted integers.',
    outputFormat: 'Print the merged sorted sequence.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '4 3\n1 4 7 10\n2 5 8\n',
    sampleOutput: '1 2 4 5 7 8 10\n',
    hiddenTestCases: [
      { input: '1 4\n5\n1 2 3 4\n', expectedOutput: '1 2 3 4 5\n' },
      { input: '3 3\n1 1 1\n1 1 1\n', expectedOutput: '1 1 1 1 1 1\n' },
      { input: '2 0\n3 9\n\n', expectedOutput: '3 9\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 6,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Codeword Rotation',
    description: 'Rotate the string left by k positions.',
    inputFormat: 'The first line contains s. The second line contains k.',
    outputFormat: 'Print the rotated string.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'cipher\n2\n',
    sampleOutput: 'pherci\n',
    hiddenTestCases: [
      { input: 'agent\n5\n', expectedOutput: 'agent\n' },
      { input: 'network\n9\n', expectedOutput: 'tworkne\n' },
      { input: 'aaaa\n1\n', expectedOutput: 'aaaa\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 7,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Dead Drop Peaks',
    description: 'Count the local peaks in the terrain array. Endpoints count if they exceed their only neighbor.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the number of peaks.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '8\n1 3 2 5 4 6 1 0\n',
    sampleOutput: '3\n',
    hiddenTestCases: [
      { input: '1\n7\n', expectedOutput: '1\n' },
      { input: '5\n5 4 3 2 1\n', expectedOutput: '1\n' },
      { input: '6\n1 2 3 4 5 6\n', expectedOutput: '1\n' },
    ],
    difficulty: 'easy',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 8,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Signal Span',
    description: 'For each signal strength, print the stock span.',
    inputFormat: ID_INPUT,
    outputFormat: 'Print the span for each position.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '7\n100 80 60 70 60 75 85\n',
    sampleOutput: '1 1 1 2 1 4 6\n',
    hiddenTestCases: [
      { input: '5\n10 20 30 40 50\n', expectedOutput: '1 2 3 4 5\n' },
      { input: '5\n50 40 30 20 10\n', expectedOutput: '1 1 1 1 1\n' },
      { input: '6\n31 27 27 30 35 29\n', expectedOutput: '1 1 2 3 5 1\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 9,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Encrypted Phrase Collapse',
    description: 'Repeated adjacent duplicate letters cancel until none remain. Print EMPTY if the final string is empty.',
    inputFormat: 'A single lowercase string s.',
    outputFormat: 'Print the reduced string or EMPTY.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: 'abbaca\n',
    sampleOutput: 'ca\n',
    hiddenTestCases: [
      { input: 'azxxzy\n', expectedOutput: 'ay\n' },
      { input: 'aaaa\n', expectedOutput: 'EMPTY\n' },
      { input: 'network\n', expectedOutput: 'network\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 10,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Checkpoint Tree Signal',
    description: 'Compute the sum of all left leaf nodes in the tree.',
    inputFormat: 'The first line contains n. The second line contains n integers in level order where -1 means null.',
    outputFormat: 'Print the sum of left leaves.',
    constraints: '1 <= n <= 2 * 10^5',
    sampleInput: '7\n3 9 20 -1 -1 15 7\n',
    sampleOutput: '24\n',
    hiddenTestCases: [
      { input: '3\n1 2 3\n', expectedOutput: '2\n' },
      { input: '1\n5\n', expectedOutput: '0\n' },
      { input: '7\n10 5 12 3 -1 -1 14\n', expectedOutput: '3\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 11,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Agent Pair Sum',
    description: 'Count pairs of dossier values whose sum equals target k.',
    inputFormat: 'The first line contains n and k. The second line contains n integers.',
    outputFormat: 'Print the number of valid pairs.',
    constraints: DEFAULT_CONSTRAINTS,
    sampleInput: '6 8\n1 7 2 6 3 5\n',
    sampleOutput: '3\n',
    hiddenTestCases: [
      { input: '5 4\n2 2 2 2 2\n', expectedOutput: '10\n' },
      { input: '4 100\n1 2 3 4\n', expectedOutput: '0\n' },
      { input: '7 6\n1 5 7 -1 5 1 2\n', expectedOutput: '3\n' },
    ],
    difficulty: 'medium',
    points: 20,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 12,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Agency Registry',
    description: 'Implement a registry abstraction. The fixed main performs ADD, UPDATE, GET, and TOP operations on agent scores.',
    inputFormat: 'The first line contains q operations.\nADD code score\nUPDATE code delta\nGET code\nTOP',
    outputFormat: 'Print results for GET and TOP. For TOP print EMPTY when no agents exist.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '7\nADD ALPHA 30\nADD BRAVO 50\nGET ALPHA\nUPDATE ALPHA 25\nGET ALPHA\nTOP\nGET BRAVO\n',
    sampleOutput: '30\n55\n55\n50\n',
    hiddenTestCases: [
      { input: '5\nTOP\nADD X1 7\nTOP\nUPDATE X1 -2\nGET X1\n', expectedOutput: 'EMPTY\n7\n5\n' },
      { input: '6\nADD RED 10\nADD BLUE 12\nUPDATE RED 5\nTOP\nGET BLUE\nGET RED\n', expectedOutput: '15\n12\n15\n' },
      { input: '4\nADD FOX 1\nUPDATE FOX 9\nUPDATE FOX -3\nTOP\n', expectedOutput: '7\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 13,
    starterCode: REGISTRY_STARTER,
    wrappers: REGISTRY_WRAPPERS,
  },
  {
    title: 'Gadget Inventory',
    description: 'Implement an inventory abstraction. The fixed main issues STOCK, USE, COUNT, and TOTAL commands.',
    inputFormat: 'The first line contains q operations.\nSTOCK type count\nUSE type count\nCOUNT type\nTOTAL',
    outputFormat: 'Print results for COUNT and TOTAL.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '7\nSTOCK DRONE 4\nSTOCK EMP 3\nCOUNT DRONE\nUSE DRONE 2\nCOUNT DRONE\nTOTAL\nCOUNT EMP\n',
    sampleOutput: '4\n2\n5\n3\n',
    hiddenTestCases: [
      { input: '4\nTOTAL\nSTOCK BUG 8\nUSE BUG 3\nCOUNT BUG\n', expectedOutput: '0\n5\n' },
      { input: '5\nSTOCK CAM 2\nSTOCK CAM 5\nUSE CAM 1\nCOUNT CAM\nTOTAL\n', expectedOutput: '6\n6\n' },
      { input: '6\nSTOCK A 1\nSTOCK B 2\nUSE B 2\nCOUNT B\nTOTAL\nCOUNT A\n', expectedOutput: '0\n1\n1\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 14,
    starterCode: INVENTORY_STARTER,
    wrappers: INVENTORY_WRAPPERS,
  },
  {
    title: 'Field Report Analyzer',
    description: 'Implement a report analyzer object. The fixed main uses ADD, HAS, LONGEST, and COUNT operations.',
    inputFormat: 'The first line contains q operations.\nADD word\nHAS word\nLONGEST\nCOUNT',
    outputFormat: 'Print results for HAS, LONGEST, and COUNT.',
    constraints: '1 <= q <= 2 * 10^5',
    sampleInput: '8\nCOUNT\nADD intel\nADD shadow\nHAS intel\nHAS echo\nLONGEST\nCOUNT\nHAS shadow\n',
    sampleOutput: '0\nYES\nNO\n6\n2\nYES\n',
    hiddenTestCases: [
      { input: '5\nADD a\nADD abcde\nLONGEST\nCOUNT\nHAS abcde\n', expectedOutput: '5\n2\nYES\n' },
      { input: '4\nHAS x\nLONGEST\nCOUNT\nADD zed\n', expectedOutput: 'NO\n0\n0\n' },
      { input: '6\nADD red\nADD carpet\nADD gala\nHAS gala\nLONGEST\nCOUNT\n', expectedOutput: 'YES\n6\n3\n' },
    ],
    difficulty: 'medium',
    points: 25,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 15,
    starterCode: ANALYZER_STARTER,
    wrappers: ANALYZER_WRAPPERS,
  },
  {
    title: 'Cipher Coverage Window',
    description: 'Given strings s and t, print the smallest substring of s that contains every character of t with multiplicity. Print IMPOSSIBLE if no such window exists.',
    inputFormat: 'The first line contains s. The second line contains t.',
    outputFormat: 'Print the minimum window or IMPOSSIBLE.',
    constraints: '1 <= |t| <= |s| <= 2 * 10^5',
    sampleInput: 'adobecodebanc\nabc\n',
    sampleOutput: 'banc\n',
    hiddenTestCases: [
      { input: 'aa\naa\n', expectedOutput: 'aa\n' },
      { input: 'a\nb\n', expectedOutput: 'IMPOSSIBLE\n' },
      { input: 'bbaac\naac\n', expectedOutput: 'aac\n' },
    ],
    difficulty: 'hard',
    points: 35,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 16,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Kth Intel Stream Merge',
    description: 'Two sorted streams are intercepted. Print the k-th smallest value in their combined sorted order without fully merging when possible.',
    inputFormat: 'The first line contains n, m, and k. The second line has n sorted integers. The third line has m sorted integers.',
    outputFormat: 'Print the k-th smallest element.',
    constraints: '1 <= n, m <= 2 * 10^5\n1 <= k <= n + m',
    sampleInput: '5 4 5\n1 4 7 10 12\n2 3 6 15\n',
    sampleOutput: '6\n',
    hiddenTestCases: [
      { input: '1 1 2\n5\n9\n', expectedOutput: '9\n' },
      { input: '3 4 4\n1 2 3\n4 5 6 7\n', expectedOutput: '4\n' },
      { input: '4 3 6\n1 3 3 9\n2 3 8\n', expectedOutput: '8\n' },
    ],
    difficulty: 'hard',
    points: 35,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 17,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Zero-Day Burst Window',
    description: 'Find the length of the shortest non-empty subarray whose sum is at least k. Values may be negative.',
    inputFormat: 'The first line contains n and k. The second line contains n integers.',
    outputFormat: 'Print the minimum length, or -1 if no valid subarray exists.',
    constraints: '1 <= n <= 2 * 10^5\n-10^9 <= ai <= 10^9\n1 <= k <= 10^15',
    sampleInput: '6 7\n2 -1 2 3 -2 4\n',
    sampleOutput: '4\n',
    hiddenTestCases: [
      { input: '3 4\n1 2 3\n', expectedOutput: '2\n' },
      { input: '3 5\n2 -1 2\n', expectedOutput: '-1\n' },
      { input: '5 3\n1 -1 1 -1 5\n', expectedOutput: '1\n' },
    ],
    difficulty: 'hard',
    points: 35,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 18,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Silent Parentheses Channel',
    description: 'Given a string of only ( and ), compute the length of the longest contiguous substring that forms a valid parentheses sequence.',
    inputFormat: 'A single string s containing only parentheses.',
    outputFormat: 'Print the maximum valid length.',
    constraints: '1 <= |s| <= 2 * 10^5',
    sampleInput: ')()())\n',
    sampleOutput: '4\n',
    hiddenTestCases: [
      { input: '((()))\n', expectedOutput: '6\n' },
      { input: '(()\n', expectedOutput: '2\n' },
      { input: '()(())\n', expectedOutput: '6\n' },
    ],
    difficulty: 'hard',
    points: 30,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 19,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Maximum Sabotage Area',
    description: 'Find the largest rectangular sabotage area in a histogram of consecutive facility heights. Width of each bar is 1.',
    inputFormat: 'The first line contains n. The second line contains n heights.',
    outputFormat: 'Print the maximum area.',
    constraints: '1 <= n <= 10^5\n0 <= h[i] <= 10^4',
    sampleInput: '6\n2 1 5 6 2 3\n',
    sampleOutput: '10\n',
    hiddenTestCases: [
      { input: '2\n2 4\n', expectedOutput: '4\n' },
      { input: '5\n1 2 3 4 5\n', expectedOutput: '9\n' },
      { input: '4\n4 3 2 1\n', expectedOutput: '6\n' },
    ],
    difficulty: 'hard',
    points: 40,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 20,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Network Traversal Cycle',
    description: 'Determine if there is a cycle in an undirected communication network.',
    inputFormat: 'The first line contains n (nodes) and m (edges). The next m lines each contain two node indices u and v (0 to n-1).',
    outputFormat: 'Print YES if there is a cycle, otherwise NO.',
    constraints: '1 <= n <= 10^5\n0 <= m <= 2 * 10^5',
    sampleInput: '4 4\n0 1\n1 2\n2 3\n3 1\n',
    sampleOutput: 'YES\n',
    hiddenTestCases: [
      { input: '3 2\n0 1\n1 2\n', expectedOutput: 'NO\n' },
      { input: '5 5\n0 1\n1 2\n0 3\n3 4\n4 0\n', expectedOutput: 'YES\n' },
      { input: '2 0\n', expectedOutput: 'NO\n' },
    ],
    difficulty: 'hard',
    points: 40,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 21,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Rogue Agent Path',
    description: 'Find the length of the longest strictly increasing subsequence of integer coordinates.',
    inputFormat: 'The first line contains n. The second line contains n integers.',
    outputFormat: 'Print the maximum length.',
    constraints: '1 <= n <= 10^5\n-10^4 <= val <= 10^4',
    sampleInput: '8\n10 9 2 5 3 7 101 18\n',
    sampleOutput: '4\n',
    hiddenTestCases: [
      { input: '6\n0 1 0 3 2 3\n', expectedOutput: '4\n' },
      { input: '7\n7 7 7 7 7 7 7\n', expectedOutput: '1\n' },
      { input: '4\n1 2 3 4\n', expectedOutput: '4\n' },
    ],
    difficulty: 'hard',
    points: 40,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 22,
    starterCode: STANDARD_STARTER,
  },
  {
    title: 'Classified Message Decode',
    description: 'A message containing letters from A-Z is encoded to numbers using A=1 to Z=26. Given a numeric string, find the number of ways to decode it modulo 10^9+7.',
    inputFormat: 'A single string of digits.',
    outputFormat: 'Print the number of valid decodings modulo 1000000007.',
    constraints: '1 <= |s| <= 10^5\nString may contain leading zeros.',
    sampleInput: '12\n',
    sampleOutput: '2\n',
    hiddenTestCases: [
      { input: '226\n', expectedOutput: '3\n' },
      { input: '06\n', expectedOutput: '0\n' },
      { input: '11111\n', expectedOutput: '8\n' },
    ],
    difficulty: 'hard',
    points: 40,
    timeLimit: 2,
    memoryLimit: 262144,
    order: 23,
    starterCode: STANDARD_STARTER,
  },
];
